name: publish

on:
  push:
    tags:
      - v*

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable && pnpm i
      - run: |
          git config user.name "xxxx"
          git config user.email "xxx@xx.xxx"
          npm version from-git --allow-same-version=true -m "xxx"
          git reset HEAD~1
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
